# Site Ayarları
title: Software Team Planner
description: "Resource planning guide and demo tools for software teams"
baseurl: "/software-team-planner"  # ← Burası değişti
url: "https://softwareprojectmanager.github.io"

# Tema
remote_theme: daattali/beautiful-jekyll

# Navigasyon Menüsü
navbar-links:
  Home: ""
  Blog: "blog"
  Demo: "demo" 
  Categories: "tags"
  About: "about"

# Site Renkleri (Sedefli beyaz tonlar)
navbar-col: "#FFFFFF"
navbar-text-col: "#2C3E50"
navbar-border-col: "#E8F4F8"
page-col: "#FFFFFF"
text-col: "#2C3E50"
link-col: "#3498DB"
hover-col: "#2980B9"
footer-col: "#F8F9FA"
footer-text-col: "#6C757D"

# Sosyal Medya
social-network-links:
  github: softwareprojectmanager

# Blog Ayarları
excerpt_length: 50
feed_show_excerpt: true
feed_show_tags: true

# SEO
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

paginate: 5
paginate_path: "/blog/page:num/"

# Markdown
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/

# Beautiful Jekyll Ayarları
beautifuljekyll-theme:
  subtitle: "Optimize your team resources efficiently"
  show-avatar: false
  nav-short: true
