name: Deploy Hugo to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      # Jekyll _posts'ları Hugo content/posts'a kopyala
      - name: Prepare Jekyll Posts for Hugo
        run: |
          mkdir -p content/posts
          find _posts -name "*.md" -exec cp {} content/posts/ \;
          
          # Dosya isimlerindeki tarihleri kaldır (Hugo için)
          cd content/posts
          for file in *.md; do
            if [[ $file =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}-(.*) ]]; then
              newname="${BASH_REMATCH[1]}"
              if [[ "$file" != "$newname" ]]; then
                mv "$file" "$newname"
              fi
            fi
          done

      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
        run: |
          hugo --gc --minify --baseURL "${{ steps.pages.outputs.base_url }}/"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
